services:
  - type: web
    name: whatsapp-gateway
    env: node
    plan: free
    rootDir: gateway
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 7000
      - key: PHONE_NUMBER_ID
        value: 874024595788234
      - key: AUTHORIZE_TOKEN
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmZmYjM2OGQ5MjkwZjlkOWU4MDA4MSIsInVzZXJUeXBlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NjAzMzU3ODcsImV4cCI6MTc2MjkyNzc4N30.aX7mjgBALqL33aeMd_k3p9_yp8TIcAkj1mhP1TeIYAQ
      - key: VERIFY_TOKEN
        value: EAA7wc9Y2A8MBPymNZCRtcsZAGg9m7bLRldz1OCI303WS76xMGuEkrc9gtpXc39BLqPkOqQQRFGbNUDzXC74O4oq1LEdtZBB0ZAfIX7Md3qNKYlifNt4BML7IZCWioxcr9rjIOZBTlIX6gf2ONqidOiMMZBDzP6dUDtDqdZAHZB4XmmYMtIHdJvgEhladZBjEZBZCDkff
      - key: ACCESS_TOKEN
        value: EAA7wc9Y2A8MBPymNZCRtcsZAGg9m7bLRldz1OCI303WS76xMGuEkrc9gtpXc39BLqPkOqQQRFGbNUDzXC74O4oq1LEdtZBB0ZAfIX7Md3qNKYlifNt4BML7IZCWioxcr9rjIOZBTlIX6gf2ONqidOiMMZBDzP6dUDtDqdZAHZB4XmmYMtIHdJvgEhladZBjEZBZCDkff

  - type: web
    name: ai-session
    env: node
    plan: free
    rootDir: services/ai-session
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 7003
      - key: PHONE_NUMBER_ID
        value: 874024595788234
      - key: AUTHORIZE_TOKEN
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmZmYjM2OGQ5MjkwZjlkOWU4MDA4MSIsInVzZXJUeXBlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NjAzMzU3ODcsImV4cCI6MTc2MjkyNzc4N30.aX7mjgBALqL33aeMd_k3p9_yp8TIcAkj1mhP1TeIYAQ
      - key: VERIFY_TOKEN
        value: EAA7wc9Y2A8MBPymNZCRtcsZAGg9m7bLRldz1OCI303WS76xMGuEkrc9gtpXc39BLqPkOqQQRFGbNUDzXC74O4oq1LEdtZBB0ZAfIX7Md3qNKYlifNt4BML7IZCWioxcr9rjIOZBTlIX6gf2ONqidOiMMZBDzP6dUDtDqdZAHZB4XmmYMtIHdJvgEhladZBjEZBZCDkff
      - key: ACCESS_TOKEN
        value: EAA7wc9Y2A8MBPymNZCRtcsZAGg9m7bLRldz1OCI303WS76xMGuEkrc9gtpXc39BLqPkOqQQRFGbNUDzXC74O4oq1LEdtZBB0ZAfIX7Md3qNKYlifNt4BML7IZCWioxcr9rjIOZBTlIX6gf2ONqidOiMMZBDzP6dUDtDqdZAHZB4XmmYMtIHdJvgEhladZBjEZBZCDkff

  - type: web
    name: bath-measure
    env: node
    plan: free
    rootDir: services/bath-measure
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 7001
      - key: PHONE_NUMBER_ID
        value: 874024595788234
      - key: AUTHORIZE_TOKEN
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmZmYjM2OGQ5MjkwZjlkOWU4MDA4MSIsInVzZXJUeXBlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NjAzMzU3ODcsImV4cCI6MTc2MjkyNzc4N30.aX7mjgBALqL33aeMd_k3p9_yp8TIcAkj1mhP1TeIYAQ
      - key: VERIFY_TOKEN
        value: EAA7wc9Y2A8MBPymNZCRtcsZAGg9m7bLRldz1OCI303WS76xMGuEkrc9gtpXc39BLqPkOqQQRFGbNUDzXC74O4oq1LEdtZBB0ZAfIX7Md3qNKYlifNt4BML7IZCWioxcr9rjIOZBTlIX6gf2ONqidOiMMZBDzP6dUDtDqdZAHZB4XmmYMtIHdJvgEhladZBjEZBZCDkff
      - key: ACCESS_TOKEN
        value: EAA7wc9Y2A8MBPymNZCRtcsZAGg9m7bLRldz1OCI303WS76xMGuEkrc9gtpXc39BLqPkOqQQRFGbNUDzXC74O4oq1LEdtZBB0ZAfIX7Md3qNKYlifNt4BML7IZCWioxcr9rjIOZBTlIX6gf2ONqidOiMMZBDzP6dUDtDqdZAHZB4XmmYMtIHdJvgEhladZBjEZBZCDkff

  - type: web
    name: livSpace
    env: node
    plan: free
    rootDir: services/livSpace
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 7002
      - key: PHONE_NUMBER_ID
        value: 874024595788234
      - key: AUTHORIZE_TOKEN
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmZmYjM2OGQ5MjkwZjlkOWU4MDA4MSIsInVzZXJUeXBlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NjAzMzU3ODcsImV4cCI6MTc2MjkyNzc4N30.aX7mjgBALqL33aeMd_k3p9_yp8TIcAkj1mhP1TeIYAQ
      - key: VERIFY_TOKEN
        value: EAA7wc9Y2A8MBPymNZCRtcsZAGg9m7bLRldz1OCI303WS76xMGuEkrc9gtpXc39BLqPkOqQQRFGbNUDzXC74O4oq1LEdtZBB0ZAfIX7Md3qNKYlifNt4BML7IZCWioxcr9rjIOZBTlIX6gf2ONqidOiMMZBDzP6dUDtDqdZAHZB4XmmYMtIHdJvgEhladZBjEZBZCDkff
      - key: ACCESS_TOKEN
        value: EAA7wc9Y2A8MBPymNZCRtcsZAGg9m7bLRldz1OCI303WS76xMGuEkrc9gtpXc39BLqPkOqQQRFGbNUDzXC74O4oq1LEdtZBB0ZAfIX7Md3qNKYlifNt4BML7IZCWioxcr9rjIOZBTlIX6gf2ONqidOiMMZBDzP6dUDtDqdZAHZB4XmmYMtIHdJvgEhladZBjEZBZCDkff

  - type: web
    name: proposal-estimator
    env: node
    plan: free
    rootDir: services/proposal-estimator
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 7004
      - key: PHONE_NUMBER_ID
        value: 874024595788234
      - key: AUTHORIZE_TOKEN
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmZmYjM2OGQ5MjkwZjlkOWU4MDA4MSIsInVzZXJUeXBlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NjAzMzU3ODcsImV4cCI6MTc2MjkyNzc4N30.aX7mjgBALqL33aeMd_k3p9_yp8TIcAkj1mhP1TeIYAQ
      - key: VERIFY_TOKEN
        value: EAA7wc9Y2A8MBPymNZCRtcsZAGg9m7bLRldz1OCI303WS76xMGuEkrc9gtpXc39BLqPkOqQQRFGbNUDzXC74O4oq1LEdtZBB0ZAfIX7Md3qNKYlifNt4BML7IZCWioxcr9rjIOZBTlIX6gf2ONqidOiMMZBDzP6dUDtDqdZAHZB4XmmYMtIHdJvgEhladZBjEZBZCDkff
      - key: ACCESS_TOKEN
        value: EAA7wc9Y2A8MBPymNZCRtcsZAGg9m7bLRldz1OCI303WS76xMGuEkrc9gtpXc39BLqPkOqQQRFGbNUDzXC74O4oq1LEdtZBB0ZAfIX7Md3qNKYlifNt4BML7IZCWioxcr9rjIOZBTlIX6gf2ONqidOiMMZBDzP6dUDtDqdZAHZB4XmmYMtIHdJvgEhladZBjEZBZCDkff
